import asyncio
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import SessionLocal
import models
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import SystemMessage, HumanMessage

pipeline_logs = []
is_pipeline_running = False


@tool
def save_smo_post_to_db(title: str, platform: str, caption: str, tag: str) -> str:
    """Saves a generated social media post into the SMO Review Queue database.

    Args:
        title: Short descriptive title for the post.
        platform: Target platform (e.g. LinkedIn, Twitter, Facebook).
        caption: The actual post text generated by the agent.
        tag: A relevant hashtag or topic tag.
    """
    db = SessionLocal()
    try:
        new_post = models.SMOPost(
            title=title,
            platform=platform,
            caption=caption,
            tag=tag,
            status="designer_review",
        )
        db.add(new_post)
        db.commit()
        pipeline_logs.append(f"Database: Saved '{title}' to SMO Queue.")
        return f"Successfully saved SMO Post: {title}"
    except Exception as e:
        db.rollback()
        return f"Database error: {e}"
    finally:
        db.close()


async def run_intelligence_pipeline():
    global is_pipeline_running, pipeline_logs
    is_pipeline_running = True
    pipeline_logs = ["System: Starting Intelligence Pipeline..."]

    try:
        llm = ChatOpenAI(model="gpt-4o", temperature=0.7)
        llm_with_tools = llm.bind_tools([save_smo_post_to_db])

        # ------------------------------------------------------------------
        # Step 1 — Discovery: find active competitor websites via LLM + HTTP
        # ------------------------------------------------------------------
        pipeline_logs.append("[Agent 1] Discovery: Identifying competitor websites...")
        try:
            from agents.discovery import discover_competitors
            competitor_urls = await discover_competitors(n=5)
            pipeline_logs.append(
                f"[Agent 1] Discovery: Found {len(competitor_urls)} active competitors: "
                + ", ".join(competitor_urls[:3]) + ("..." if len(competitor_urls) > 3 else "")
            )
        except Exception as e:
            competitor_urls = []
            pipeline_logs.append(f"[Agent 1] Discovery: Failed — {e}. Continuing with cached competitors.")

        # ------------------------------------------------------------------
        # Step 2 — Scoring: scrape and score each competitor's digital presence
        # ------------------------------------------------------------------
        pipeline_logs.append("[Agent 2] Scoring: Analysing competitor digital presence...")
        scores = {}
        if competitor_urls:
            try:
                from agents.analysis import analyze_competitor_batch
                scores = await analyze_competitor_batch(competitor_urls)
                pipeline_logs.append(
                    f"[Agent 2] Scoring: Scored {len(scores)} competitors. "
                    + "Top: " + max(scores, key=scores.get, default="none")
                )

                # Persist scores to Competitor table
                db = SessionLocal()
                try:
                    for url, score in scores.items():
                        name = url.replace("https://", "").replace("www.", "").split("/")[0]
                        existing = db.query(models.Competitor).filter(models.Competitor.website_url == url).first()
                        if existing:
                            existing.presence_score = int(score)
                        else:
                            db.add(models.Competitor(
                                name=name,
                                website_url=url,
                                presence_score=int(score),
                                is_active=1,
                            ))
                    db.commit()
                    pipeline_logs.append(f"[Agent 2] Scoring: Saved {len(scores)} competitor scores to database.")
                except Exception as db_err:
                    db.rollback()
                    pipeline_logs.append(f"[Agent 2] Scoring: DB save failed — {db_err}")
                finally:
                    db.close()
            except Exception as e:
                pipeline_logs.append(f"[Agent 2] Scoring: Failed — {e}")
        else:
            pipeline_logs.append("[Agent 2] Scoring: No URLs to score — loading from database.")
            db = SessionLocal()
            try:
                comps = db.query(models.Competitor).filter(models.Competitor.is_active == 1).all()
                scores = {c.website_url: c.presence_score for c in comps}
            except Exception:
                scores = {}
            finally:
                db.close()

        # ------------------------------------------------------------------
        # Step 3 — Gap Analysis: ask GPT-4o to identify content gaps
        # ------------------------------------------------------------------
        pipeline_logs.append("[Agent 3] Gap Analysis: Identifying content opportunities...")
        gap_summary = ""
        if scores:
            scores_text = "\n".join(
                f"- {url}: {score}/100" for url, score in sorted(scores.items(), key=lambda x: x[1], reverse=True)
            )
            gap_response = await llm.ainvoke([
                SystemMessage(content=(
                    "You are a digital marketing strategist for Harshwal & Company LLP, a CPA firm. "
                    "Analyse competitor presence scores and identify 3 specific content gaps Harshwal can exploit. "
                    "Be concise — one sentence per gap."
                )),
                HumanMessage(content=f"Competitor presence scores:\n{scores_text}\n\nIdentify 3 content gaps."),
            ])
            gap_summary = gap_response.content.strip()
            pipeline_logs.append(f"[Agent 3] Gap Analysis: {gap_summary[:120]}...")
        else:
            gap_summary = "Competitors lack thought leadership content on tax planning and tribal compliance."
            pipeline_logs.append("[Agent 3] Gap Analysis: Using default gap (no score data available).")

        # ------------------------------------------------------------------
        # Step 4 — Strategy synthesis
        # ------------------------------------------------------------------
        pipeline_logs.append("[Agent 4] Strategy: Synthesising outreach strategy...")
        strategy_context = (
            f"Competitor analysis complete. Gaps identified:\n{gap_summary}\n\n"
            "Harshwal strengths: full-service CPA, tribal government expertise (Blue Arrow), advisory for growth companies."
        )
        pipeline_logs.append("[Agent 4] Strategy: Context ready for content generation.")

        # ------------------------------------------------------------------
        # Step 5 — Content generation: write and save a targeted SMO post
        # ------------------------------------------------------------------
        pipeline_logs.append("[Agent 5] Content: Generating targeted SMO post...")
        system_prompt = (
            "You are the Harshwal Intelligence Orchestrator. "
            f"{strategy_context}\n\n"
            "Write a highly targeted LinkedIn post that exploits a competitor's weakness identified above. "
            "You MUST use the `save_smo_post_to_db` tool to save it. "
            "title should be under 60 chars, caption under 300 chars, tag should be a hashtag."
        )

        messages = [SystemMessage(content=system_prompt), HumanMessage(content="Generate the post for LinkedIn.")]
        response = await llm_with_tools.ainvoke(messages)

        if response.tool_calls:
            for tool_call in response.tool_calls:
                pipeline_logs.append(f"Agent thought: Invoking tool {tool_call['name']}")
                tool_msg = save_smo_post_to_db.invoke(tool_call)
                pipeline_logs.append(f"Final output: {tool_msg}")
        else:
            pipeline_logs.append(f"Final output: {response.content}")

    except Exception as e:
        pipeline_logs.append(f"Pipeline Error: {str(e)}")
    finally:
        pipeline_logs.append("System: Pipeline execution complete.")
        is_pipeline_running = False
